### ISSUE TITLE
Great job. Solving some issues...

### ISSUE THREAD

**Issue by espitgn** [RepoWeaver/MateBook-X-Pro-2020-OpenCore#1]
Hi RepoWeaver:

Thanks for your work! I''m been working with a matebook X Pro 2020 version with Big Sur. Now it's very stable, with a low battery drain and Windows friendly (Win 11 works flawessly booting from Opencore Menu),  but I'm absolutely stuck with the upgrade to Monterey. 

Cheers

**Comment by RepoWeaver** [comment]
I would like to check out your battery drain settings it’s sort of hard to have longer battery life and performance when I need it, I upgraded to Monterey with only Bluetooth being the issue so I had to look at the opencore guide

**Comment by espitgn** [comment]
Hi,

Now I see the pkg consumption tested with Intel Power Gadget is very similar than mine. (about 0.6-0.8 W in idle). With my build, battery lasts for 4-5 h in regular use (internet, office applications, etc..). I'll  test with yours, it should be similar.

About black screen issue, don't show in my Big Sur build. I see your SSDT-LID is different than mine. I've tested my SSDT-LID (+ a acpi patch) on your build and runs ok, without any issue. The black screen on boot disappears and clamshell sleeps computer as well. 

If you want, I can attach your config.plist modified and my SSDT-LID.

Cheers

**Comment by RepoWeaver** [comment]
Yep that would be helpful thanks, just to note, I am now currently running Monterey so I'll see if anything Breaks.

Thanks

**Comment by espitgn** [comment]
Here they are. SSDT-LID and config.plist with related ACPI patch (look at item 17 in ACPI->Patch)

Test it and comment the results, please
[LID+config.zip](https://github.com/RepoWeaver/MateBook-X-Pro-2020-OpenCore/files/7798857/LID%2Bconfig.zip)
.

**Comment by RepoWeaver** [comment]
It didn't work as I still had to close and open the lid (this isn't a problem currently for me) we could both work on it and see if it will work, then I'll update the efi folder, not sure why it didn't work though.

**Comment by espitgn** [comment]
It's strange... It's working for me without issue. Did you clean nvram before test it? It's important.

**Comment by RepoWeaver** [comment]
it might be because of Monterey, I did clear nvram. Because stuff has been broken but work arounds were there, in Big Sur most stuff are stable

**Comment by espitgn** [comment]
I use it in Monterey and it works. But I see I didn't talk about the bootflag "-igfxblr". I put it in the config.list that I sent.  did you use my config.plist or made changes in yours?

**Comment by espitgn** [comment]
A new config.plist with the solution for the huge battery draining after sleep (+ black screen solved and correct sleep closing lid).

Cheers
[config.plist.zip](https://github.com/RepoWeaver/MateBook-X-Pro-2020-OpenCore/files/7804837/config.plist.zip)

**Comment by RepoWeaver** [comment]
I used your config and it works just really long boot times as I can see I'm stuck here ![image](https://user-images.githubusercontent.com/91159194/148113001-dc15c8de-3b90-478f-ae13-3124c6d2a9e8.jpeg)

**Comment by RepoWeaver** [comment]
Could you send your EFI as is, just remove SMBIOS because something doesn't seem right, all of my kext's are up to date so I'm guessing our apci's aren't the same that's why I would like to see your Complete EFI folder (ZIP)

**Comment by espitgn** [comment]
Hi, I'm working basically with your EFI, but changing the ssdt-lid.aml (in ACPI folder) and some little changes in config.plist. 
I disabled CFG Lock and enable dmvt 64 (flashing bios), but I undestand that not all people have done this, then I've attached two configurations (With and without CFG LOCK disabled).

My MBXP model is MACHC-WAH9D (without dGPU), it could be different that yours.

Here is the complete EFI. For me it's working without issues

[https://drive.google.com/file/d/1s2FQb-JmKA1GyrMEuxOVQdL-yNgVeVgm/view?usp=sharing](url)

**Comment by RepoWeaver** [comment]
Thank you and I've had a chance to test it completely, I was completely an idiot, I forgot I should be using config NOT CFG Lock not dvmt 64.plist and it worked perfectly every time, I will publish the EFI (With your permission) stable with both Big Sur and Monterey. Thank you very much for your help and the community will know you helped :)
