### ISSUE TITLE
Improvements for the new release

### ISSUE THREAD

**Issue by espitgn** [RepoWeaver/MateBook-X-Pro-2020-OpenCore#2]
HI RepoWave:

thank you for your gratitude. I fell happy to help you and the community.

I've been looking the config.plist on the last release. It could be a good idea talk in your readme about the possibility of disabling CFG Lock and enabling dmvt 64. The power management improvement disabling CFG Lock is quite good, and the procedure (customizing BIOS) is quite easy to follow. (look at [this link](https://github.com/ske1996/Matebook-x-pro-2019-Hackintosh-newest/blob/main/readme-en.md): "How to disable CFG Lock" and "Change dvmt to 64 mb" in "After installation" section).

These guides work without issue in our MBXP 2020 (tested with BIOS 1.19 and 1.21 versions). Each guide shows the changes to do in config.plist as well).

Cheers

**Comment by RepoWeaver** [comment]
Thanks for that, always a great help

**Comment by RepoWeaver** [comment]
Is there any more ways to get more battery life at least 5-6 hours max if your able to build the kext to work well that would be a good thing to look at

**Comment by espitgn** [comment]
HI. I took a deeper look at your ACPI folder, and I found some things that didn't understand:

SSDT-BIOS: It adds a method (called _QBF). But this method is already include into MBXP 2020 DSDT. Then, it's not necessary.

SSDT-ALSD: It seems a copy of the SSDT suitable for MBXP 2018. As you know, this laptop runs a very different BIOS, specially for the battery and light sensor management. Then, obviously, never works in MBXP 2020. I'm working in a mod for SSDT-BAT that manage reasonably well ALSD (automatic keyboard backlight on darkness), but unfortunatelly it breaks some Windows features (I needs dual boot for my job) and It's now usable for me at this moment.

SSDT-BAT. There is a refference of XCWT Method, and the ECWT->XCWT patch is disable. It would be better change by ECWT in SSDT-BAT and enable ECWT->XCWT patch in config.plist, wouldn't it?

Maybe I'm wrong, but seems a bit strange...

Cheers

**Comment by RepoWeaver** [comment]
Would it be possible to make these changes so I can update the releases
because I’m extremely busy with work if your not able to that’s completely
fine.

**Comment by espitgn** [comment]
Of course. I'll attach EFI with these changes soon.

**Comment by RepoWeaver** [comment]
I've added you as a collaborator as I'll be moving to windows for a few just so I can re-evaluate the battery times

**Comment by nenkoru** [comment]
> Of course. I'll attach EFI with these changes soon.

Any news on changing those references?

**Comment by espitgn** [comment]
> > Of course. I'll attach EFI with these changes soon.
> 
> Any news on changing those references?

I'm quite busy till february 6th. Sorry!

**Comment by nenkoru** [comment]
> > > Of course. I'll attach EFI with these changes soon.
> > 
> > 
> > Any news on changing those references?
> 
> I'm quite busy till february 6th. Sorry!

If you have any work done in your fork of this repo, then it would be great if you can push it so that we can take a look into it!

**Comment by RepoWeaver** [comment]
Please wait, if there's bugs or anything and your build is broken because of a rushed release then thats not okay.

**Comment by nenkoru** [comment]
> Please wait, if there's bugs or anything and your build is broken because of a rushed release then thats not okay.
> […](#)
> On Jan 26 2022, at 5:33 pm, Ruslan Chernenko ***@***.***> wrote: > > > Of course. I'll attach EFI with these changes soon. > > Any news on changing those references? > > I'm quite busy till february 6th. Sorry! If you have any work done in your fork of this repo, then it would be great if you can push it so that we can take a look into it! — Reply to this email directly, view it on GitHub ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2FRepoWeaver%2FMateBook-X-Pro-2020-OpenCore%2Fissues%2F2%23issuecomment-1022429165&recipient=cmVwbHkrQVZYUFZHV1FQWFFCSzJBT01LSllSTUY3N1ZUTzdFVkJOSEhFQ1VNUUZVQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVXPVGT6A6SQBXIOLMFDMRLUYAV67ANCNFSM5LNTQXHQ&recipient=cmVwbHkrQVZYUFZHV1FQWFFCSzJBT01LSllSTUY3N1ZUTzdFVkJOSEhFQ1VNUUZVQHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you commented.

I am not rushing to apply changes of his straight away, as long as it's open-source I would have liked to collaborate to proceed to make what the user was making.
(I am a developer myself)

**Comment by nenkoru** [comment]
@espitgn, thank you indeed for your time contributing your changes and upgrading opencore to 0.7.7, I saw they added new features so I assume you had fun time changing the config!
