### ISSUE TITLE
Camera not working 

### ISSUE THREAD

**Issue by pepelako1** [RepoWeaver/MateBook-X-Pro-2020-OpenCore#5]
Camera vendorid13d3:56c6 not working, black screen, ports mapped, the cam is in devoce hs04 internal but no luck, any ideas? In Linux work

**Comment by pepelako1** [comment]
![Uploading A9F08FF4-B066-4C3C-ACC7-F3B9878DDC04.jpeg…]()

**Comment by pepelako1** [comment]
![80F417EB-A3DE-4283-B5E5-B390D293D75E](https://user-images.githubusercontent.com/30156188/155912581-7f99e162-6fe3-4e8f-83a5-ecf74c318751.jpeg)
![310361E3-E0BF-472E-B23C-206563C849A5](https://user-images.githubusercontent.com/30156188/155912589-6ead28f9-1f94-4b39-bf58-00b686b18f37.jpeg)
![0D1FFDDA-0F05-44FC-8D37-8F93A9B9FE5C](https://user-images.githubusercontent.com/30156188/155912591-bd0e3b0d-a4de-40b8-a5f9-bf4a79e2f9f4.jpeg)
![255B8ACA-0BA6-4AF9-8374-C5B112E71F70](https://user-images.githubusercontent.com/30156188/155912596-334c1e36-b591-4fd1-b7e2-37df2050421b.jpeg)

**Comment by RepoWeaver** [comment]
I have looked into this and cannot seem to understand how. It is working on my laptop and current EFI and other's, maybe you have a different model on your MateBook.
