### ISSUE TITLE
Enable touchsceen

### ISSUE THREAD

**Issue by borotj** [RepoWeaver/MateBook-X-Pro-2020-OpenCore#6]
Hello,

Thanks for the work in this repo, it helped me a lot ;)

I just had an issue with my drive (Samsung PM981 1TB). I replaced it with a WD Black SN770 1TB and it works like a charm.

Can someone give me a way to enable touchscreen please ? It was a really good feature on Windows.

**Comment by RepoWeaver** [comment]
I haven't found a complete way to enable touchscreen without something else breaking but there may be guides somewhere else

**Comment by espitgn** [comment]
Sure. In config.plist, ACPI, Add, look for item  19 (SSDT-TPLT.aml) and set "Enabled" option to "NO". Restart and you'll have touchscreen working. But perhaps It's not a good idea. Touchscreen drains battery quickly.

**Comment by catfrog** [comment]
Just found your Last comment on how to activate the Touch Screen.
Would have been nice, but did not work for me, any idea?
