### ISSUE TITLE
Touchpad did not work on my end without VoodooI2C ! 

### ISSUE THREAD

**Issue by boyer-nicolas** [RepoWeaver/MateBook-X-Pro-2020-OpenCore#7]
Hey, Thanks for this repo, helped me so much. However my trackpad did not work (i7 version) without this 
: https://github.com/VoodooI2C/VoodooI2C 
Hope this can help some people too.

I'm currently trying to enable external display support and trying to make the camera display something else than a black screen.

**Comment by RepoWeaver** [comment]
Thanks for the help, i'm not sure if there is an issue with the i7 version when coming to external display support or camera. I don't have an i7 version so I am sorry I can't help with that. For me or the i5 version they worked out of box and improved with the most recent release of the EFI files.
